//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        public string Name { get; set; }
        public long TotalMatchesPlayed { get; set; }
        public long TotalMatchesWon { get; set; }
        public string FavouriteServer { get; set; }
        public long UniqueServers { get; set; }
        public string FavouriteGameMode { get; set; }
        public double AverageScoreboardPercent { get; set; }
        public long MaximumMatchesPerDay { get; set; }
        public double AverageMatchesPerDay { get; set; }
        public string LastMatchPlayed { get; set; }
        public double KillToDeathRatio { get; set; }
    
        public virtual BestPlayer BestPlayer { get; set; }
        public virtual ServerStat ServerStat { get; set; }
    }
}
