//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoreboard
    {
        public long Id { get; set; }
        public long MatchId { get; set; }
        public string Name { get; set; }
        public long Frags { get; set; }
        public long Kills { get; set; }
        public long Deaths { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
