//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopFiveMap
    {
        public long Id { get; set; }
        public string ServerEndpoint { get; set; }
        public string Map { get; set; }
    
        public virtual ServerStat ServerStat { get; set; }
    }
}
